server:
  port: 8087
  servlet:  #predicates do gateway
    context-path: '/ead-authuser/'
spring:
  application:
    name: ead-authuser-service #nome que vai ser visto no eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
       lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url: #name eureka do course
      course: 'http://ead-course-service/ead-course'

eureka: #configuracoes do eureka
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
