server:
  port: 8082
  servlet: #predicates do gateway
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service #nome que vai ser visto no eureka
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
ead:
  api:
    url: #passa o nome do eureka do authuser
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka: #configuracoes do eureka
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost